taximaster:
  api:
    base_url: 'https://incity.dyndns.org:31185/common_api/1.0'
    secret: 'secret'

datasource:
  internal:
    url: jdbc:h2:./payment-gateway-taximaster
    username: sa
    password: ''
