taximaster:
  api:
    base_url: 'https://host:port/common_api/1.0'
    secret: 'secret'

datasource:
  internal:
    url: 'jdbc:h2:./payment-gateway-taximaster'
    username: 'sa'
    password: ''
    start_tcp_server: true

retry:
  strategy: '{"intervals": [{"interval": 300, "quantity": 2}, {"interval": 600, "quantity": 2}, {"interval": 1200, "quantity": 2} ]}'

sberbank:
  allowed_subnets:
    - '194.186.207.0/24'
    - '194.54.14.0/24'
    - '192.168.0.0/16'
    - '127.0.0.0/8'
  allowed_hosts:
    - 'localhost'
    - 'ip6-localhost'
  allowed_serv_values:
    - '2'
  pay_ch_cash:
    - 'KASSA'
    - 'US_N'
    - 'AGENT'
  pay_ch_cashless:
    - 'KASSA_V'
    - 'F_190'
    - 'US_V'
    - 'SBOL'
    - 'MOB'
    - 'APAY'
  pay_ch_default: 'SBERBANK_CASHLESS'

ccb:
  secret: 'ccb_secret'
  allowed_subnets:
    - '127.0.0.0/8'
    - '192.168.0.0/16'
    - '10.0.0.0/8'
    - '172.16.0.0/12'
    - '94.138.149.210'
    - '94.138.149.208'
    - '94.138.149.36'
    - '89.250.213.20'
    - '89.250.213.22'
    - '89.250.209.99'
    - '94.138.149.32'
  allowed_hosts:
    - 'localhost'
    - 'ip6-localhost'
  allowed_serv_values:
    - '2'
    - '3'
    - '4'

synchronization:
  interval_sec: 60
  drivers: true
  crews: false

source_type_map:
  SBERBANK_CASH: 'Сбербанк наличные'
  SBERBANK_CASHLESS: 'Сбербанк безналичный'

logging:
  audit:
    templates:
      - path: '/jbilling/pay/sberbank2'
        action: 'check'
        message: 'Запрос баланса - ИД Водителя: {ACCOUNT}, SERV: {SERV}'
      - path: '/jbilling/pay/sberbank2'
        action: 'payment'
        message: 'Проведение платежа - ИД Водителя: {ACCOUNT}, Сумма: {AMOUNT}, ИД Платежа: {PAY_ID}, Дата: {PAY_DATE}, PAY_CH: {PAY_CH}, SERV: {SERV}'
  request_log:
    schedule: 'every day 03:00'
    max_age_days: 31
