taximaster:
  api:
    base_url: 'https://host:port/common_api/1.0'
    secret: 'secret'

datasource:
  internal:
    url: jdbc:h2:./payment-gateway-taximaster
    username: sa
    password: ''

retry:
  strategy: '{"intervals": [{"interval": 300, "quantity": 2}, {"interval": 600, "quantity": 2}, {"interval": 1200, "quantity": 2} ]}'

allowed_subnets:
  - '194.186.207.0/24'
  - '194.54.14.0/24'
  - '192.168.0.0/16'
  - '127.0.0.0/8'

allowed_hosts:
  - 'localhost'
  - 'ip6-localhost'

allowed_serv_values:
  - '2'
